# https://github.com/Huachao/vscode-restclient

POST http://localhost:3000/user

###

GET http://localhost:3000/user

###

GET http://localhost:3000/user/1

###

PUT http://localhost:3000/user/1

###

DELETE http://localhost:3000/user/1

###
